CREATE TABLE IF NOT EXISTS product_group
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_group_name VARCHAR(255)                            NOT NULL,
    created            TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated            TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_product_group PRIMARY KEY (id)
);

INSERT INTO product_group (product_group_name)
VALUES ('Group 1'),
       ('Group 2'),
       ('Group 3');
