CREATE TABLE IF NOT EXISTS warehouse
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    warehouse_name VARCHAR(255)                            NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_warehouse PRIMARY KEY (id)
);

INSERT INTO warehouse (warehouse_name)
VALUES ('Warehouse 1'),
       ('Warehouse 2'),
       ('Warehouse 3');
