CREATE TABLE IF NOT EXISTS product_stock
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id   BIGINT,
    warehouse_id BIGINT,
    quantity     INTEGER                                 NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_product_stock PRIMARY KEY (id)
);

INSERT INTO product_stock (product_id, warehouse_id, quantity)
VALUES
    (1, 1, 10),
    (2, 2, 5),
    (3, 1, 8),
    (4, 3, 12),
    (5, 2, 18);
